version: '3.3'

services:
  orbits:
    image : node:16
    depends_on:
      - "mongo"
    network_mode: "host"
    user: node:998 #cf https://docs.npmjs.com/cli/v7/using-npm/scripts#user
    command: "npm run build-and-start"
    working_dir: "/app"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      
  mongo:
    image: mongo
    volumes:
      - ~/mongors/data:/data/db
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "local-dev-mongo" ]
    network_mode: "host"

