packages:
  - core/actions
  - helpers
  - cli
  - packages/*

catalog:
  '@tsconfig/node16': ^16.1.5
  '@tsconfig/node22': ^22.0.2
  '@types/jasmine': ^4.6.5
  '@types/node': ^18.19.130
  jasmine: ^4.6.0
  mongoose: ^6.13.8
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.3.0
  ts-node: ^10.9.2
  ts-node-dev: ^2.0.0
  tslib: ^2.8.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  winston: ^3.18.3
