packages:
  - core/actions
  - helpers
  - cli
  - packages/*

catalog:
  typescript: ^5.8.3
  mongoose: ^6.13.6
  winston: ^3.8.2

  jasmine: ^4.5.0
  ts-node: ^10.9.1
  ts-node-dev: ^2.0.0
  tslib: ^2.4.1
  tsx: ^4.19.0

  prettier: ^3.5.3
  prettier-plugin-organize-imports: ^4.1.0

  "@tsconfig/node16": ^16.1.3
  "@tsconfig/node22": ^22.0.0
  "@types/node": ^18.11.14
  "@types/jasmine": ^4.3.1
