packages:
  - src/core/actions
  - src/helpers
  - src/cli
  - src/packages/*

catalog:
  typescript: ^4.9.4
  mongoose: ^6.8.1
  winston: ^3.8.2

  jasmine: ^4.5.0
  ts-node: ^10.9.1
  ts-node-dev: ^2.0.0
  tslib: ^2.4.1
  tsx: ^3.12.7

  "@tsconfig/node16": ^16.1.3
  "@types/node": ^18.11.14
  "@types/jasmine": ^4.3.1
