name: Report a bug
description: Create a report to help us improve
body:
 - type: markdown
   attributes:
    value: |
     Hi, thank you for taking the time to create an issue! Before you get started, please ensure the following are correct:

     - I'm using the latest version of Orbits
     - There's [no other issue](https://github.com/LaWebcapsule/orbits/issues?q=is%3Aissue) that already describes the problem.
 - type: textarea
   attributes:
    label: Describe the Bug
    description: A clear and concise description of what the bug is.
   validations:
    required: true
 - type: textarea
   attributes:
    label: To Reproduce
    description:
     Steps to reproduce the behavior. Contributors should be able to follow the steps provided in order to reproduce
     the bug.
   validations:
    required: true
 - type: input
   attributes:
    label: Orbits Version
    placeholder: 1.0.0
   validations:
    required: true
