blank_issues_enabled: false
contact_links:
 - name: Ask a question
   url: https://join.slack.com/t/orbitsgroupe/shared_invite/zt-394jwf72o-utjAV~odD32GhyKnhjnDFQ
   about: Please ask and answer questions here.
