name: Report a docs inaccuracy
description: When something is wrong or incorrect in the docs
labels: Documentation
body:
 - type: markdown
   attributes:
    value: |
     Hi, thank you for taking the time to create an issue! 
 - type: input
   attributes:
    label: Page
    description: A direct link to the page with the problem
   validations:
    required: true
 - type: textarea
   attributes:
    label: Describe the Inaccuracy
    description: A clear and concise description of what the problem is
   validations:
    required: true
